# Generated by Django 4.2.8 on 2023-12-24 13:23

from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuicknavButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('style', models.CharField(max_length=10)),
                ('icon', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('divider', models.BooleanField(default=False)),
                ('link', models.CharField(default='#', max_length=250)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('order', 'title'),
                'unique_together': {('order', 'title')},
            },
        ),
    ]
